export enum RouteNames {
  LOGIN = "/login",
  REGISTER = "/register",
  DASHBOARD = "/dashboard",
  START = `${DASHBOARD}/start`,
  ALL_PATIENTS = `${DASHBOARD}/allPatients`,
  SPECIALIZATIONS = `${DASHBOARD}/specializations`,
  CLINIC_AFFILIATION = `${DASHBOARD}/clinicAffiliations`,
  ADD_CLINIC = `${DASHBOARD}/addClinic`,
  ALL_CLINICS = `${DASHBOARD}/allClinics`,
  EDIT_CLINIC = `${DASHBOARD}/editClinic`,
  ACCOUNT_MANAGEMENT = `${DASHBOARD}/accountManagement`,
  ALL_DOCTORS = `${DASHBOARD}/allDoctors`,
  MAKE_APPOINTMENT = `${DASHBOARD}/doctorsSelection/makeAppointment`,
  MY_APPOINTMENTS = `${DASHBOARD}/myAppointments`,
  UNAUTHORIZED = "/unauthorized",
  DOCTORS_SELECTION = `${DASHBOARD}/doctorsSelection`,
}
