export * from "./yup/schemas/addClinic"
export * from "./yup/schemas/changePassword"
export * from "./yup/schemas/login"
export * from "./yup/schemas/makeAppointment"
export * from "./yup/schemas/register"
export * from "./yup/schemas/updateUserInfo"
export * from "./yup/schemas/uploadPhoto"
