export * from "./api/getPatients"
export { setQueryParams, default as patientsSlice } from "./store/patientsSlice"
export * from "./store/patientsThunks"
export { default as AllPatients } from "./views/AllPatients"
export { default as SinglePatient } from "./views/SinglePatient"
export * from "./api/getSinglePatient"
